CREATE TABLE "contact_page_content" (
	"id" text PRIMARY KEY NOT NULL,
	"intro1_en" text DEFAULT '' NOT NULL,
	"intro2_en" text DEFAULT '' NOT NULL,
	"intro3_en" text DEFAULT '' NOT NULL,
	"intro4_en" text DEFAULT '' NOT NULL,
	"company_heading_en" text DEFAULT '' NOT NULL,
	"office_address_en" text DEFAULT '' NOT NULL,
	"intro1_bg" text DEFAULT '' NOT NULL,
	"intro2_bg" text DEFAULT '' NOT NULL,
	"intro3_bg" text DEFAULT '' NOT NULL,
	"intro4_bg" text DEFAULT '' NOT NULL,
	"company_heading_bg" text DEFAULT '' NOT NULL,
	"office_address_bg" text DEFAULT '' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "home_faq_content" (
	"id" text PRIMARY KEY NOT NULL,
	"intro_en" text DEFAULT '' NOT NULL,
	"what_we_do_en" text DEFAULT '' NOT NULL,
	"requirements_en" text DEFAULT '' NOT NULL,
	"academy_en" text DEFAULT '' NOT NULL,
	"booking_en" text DEFAULT '' NOT NULL,
	"journal_en" text DEFAULT '' NOT NULL,
	"vision_en" text DEFAULT '' NOT NULL,
	"question_about_en" text DEFAULT '' NOT NULL,
	"question_what_we_do_en" text DEFAULT '' NOT NULL,
	"question_requirements_en" text DEFAULT '' NOT NULL,
	"question_academy_en" text DEFAULT '' NOT NULL,
	"question_booking_en" text DEFAULT '' NOT NULL,
	"question_journal_en" text DEFAULT '' NOT NULL,
	"intro_bg" text DEFAULT '' NOT NULL,
	"what_we_do_bg" text DEFAULT '' NOT NULL,
	"requirements_bg" text DEFAULT '' NOT NULL,
	"academy_bg" text DEFAULT '' NOT NULL,
	"booking_bg" text DEFAULT '' NOT NULL,
	"journal_bg" text DEFAULT '' NOT NULL,
	"vision_bg" text DEFAULT '' NOT NULL,
	"question_about_bg" text DEFAULT '' NOT NULL,
	"question_what_we_do_bg" text DEFAULT '' NOT NULL,
	"question_requirements_bg" text DEFAULT '' NOT NULL,
	"question_academy_bg" text DEFAULT '' NOT NULL,
	"question_booking_bg" text DEFAULT '' NOT NULL,
	"question_journal_bg" text DEFAULT '' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
